# Replace the following variables with your actual values
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTc4MjE4MWIxMzk0N2UxZjE5ZGRhMyIsInJvbGUiOiJkb25vciIsImlhdCI6MTc0ODQyMTg1NywiZXhwIjoxNzQ4NTA4MjU3fQ.1dOUvuzVutTqgVJR_duaS4x3dJ9R5Kzi86VE4PLFFH0
@donation_id=6834b911d7935e36b89387f4

@help_request_id=6834b65343ebf46de667761a

### Create Donation
POST http://localhost:3000/donations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Winter Jacket",
  "message": "Hope this helps someone stay warm this winter!",
  "category": "clothing",
  "helpRequest": "{{help_request_id}}"
}

###

### Get All Donations
GET http://localhost:3000/donations
Authorization: Bearer {{token}}

###

### Get Donation by ID
GET http://localhost:3000/donations/{{donation_id}}
Authorization: Bearer {{token}}

###

### Update Donation
PUT http://localhost:3000/donations/{{donation_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Winter Jacket (Updated)",
  "message": "Still gently used, added hood",
  "category": "clothing",
}
###

### Delete Donation
DELETE http://localhost:3000/donations/{{donation_id}}
Authorization: Bearer {{token}}

###


### Get donations overview
GET http://localhost:3000/donations/analytics/overview
