### Base URL
@baseUrl=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTc4MjE4MWIxMzk0N2UxZjE5ZGRhMyIsInJvbGUiOiJkb25vciIsImlhdCI6MTc0ODI2NjI4MSwiZXhwIjoxNzQ4MzUyNjgxfQ.7ay8vPuAN2UAPHNKXG1zxtbQTFvFpjH6jhw-i2jx8p8
@helpRequestId=68347f75f7a0d872f98745f7

### Create Help Request
POST {{baseUrl}}/help-requests
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Need clothes for winter",
  "description": "I am looking for warm clothes for my kids.",
  "category": "other"
}

### Get All Help Requests
GET {{baseUrl}}/help-requests

### Get Help Request by ID
GET {{baseUrl}}/help-requests/{{helpRequestId}}

### Update Help Request
PUT {{baseUrl}}/help-requests/{{helpRequestId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Need warm winter jackets",
  "description": "Preferably for ages 5-10."
}

### Delete Help Request
DELETE {{baseUrl}}/help-requests/{{helpRequestId}}
Authorization: Bearer {{token}}
