### Base URL
@baseUrl=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzRiNjBmNDNlYmY0NmRlNjY3NzYxNyIsInJvbGUiOiJyZWNpcGllbnQiLCJpYXQiOjE3NDg0MjE5NTYsImV4cCI6MTc0ODUwODM1Nn0.EFZLxODTxTGe3etQMhBI9mQxvgPkdhqalK5rTZqEEEM
@helpRequestId=6834b65343ebf46de667761a

### Create Help Request
POST {{baseUrl}}/help-requests
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Need clothes for winter",
  "description": "I am looking for warm clothes for my kids.",
  "category": "clothing"
}

### Get All Help Requests
GET {{baseUrl}}/help-requests

### Get Help Request by ID
GET {{baseUrl}}/help-requests/{{helpRequestId}}

### Update Help Request
PUT {{baseUrl}}/help-requests/{{helpRequestId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Need warm winter jackets",
  "description": "Preferably for ages 5-10."
}

### Delete Help Request
DELETE {{baseUrl}}/help-requests/{{helpRequestId}}
Authorization: Bearer {{token}}

### Get Open Help Requests
GET {{baseUrl}}/help-requests/open

### Get logged-in user's Help Requests
GET {{baseUrl}}/help-requests/my
Authorization: Bearer {{token}}