### Register a new user
POST https://not-an-api.com/auth/register
Content-Type: application/json

{
  "name": "Eleanor Rigby",
  "role": "donor",
  "email": "eleanor@rigby.com",
  "password": "eleanorPassword123"
}

####

### Register a new user recipient
POST https://not-an-api.com/auth/register
Content-Type: application/json

{
  "name": "Father McKenzie",
  "role": "recipient",
  "email": "father@mckenzie.com",
  "password": "fatherPassword123"
}

####

### Login user Eleanor Rigby (Donor)
POST https://not-an-api.com/auth/login
Content-Type: application/json

{
  "email": "eleanor@rigby.com",
  "password": "eleanorPassword123"
}

####

### Login user Father McKenzie (Recipient)
POST https://not-an-api.com/auth/login
Content-Type: application/json

{
  "email": "father@mckenzie.com",
  "password": "fatherPassword123"
}

####

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2Q2ZDEzNjQ2ZDM4ODVmYWFiZjhkMSIsInJvbGUiOiJkb25vciIsImlhdCI6MTc0ODk0NzQ5NCwiZXhwIjoxNzQ5MDMzODk0fQ.m9LIO2EoAt1v2VAOnp8fYvD4GOFhPBoKqtXWQMSH9t8

### Get current user (Replace TOKEN after login)
GET https://not-an-api.com/auth/me
Authorization: Bearer {{token}}

####


#### Register a new user 
POST https://not-an-api.com/auth/register
Content-Type: application/json

{
  "name": "Lucy in the Sky With Diamonds",
  "role": "recipient",
  "email": "lucy@diamonds.com",
  "password": "lucyPassword123"
}

####

### Login user
POST https://not-an-api.com/auth/login
Content-Type: application/json

{
  "email": "lucy@diamonds.com",
  "password": "lucyPassword1234"
}

####