### Base URL
@baseUrl=https://not-an-api.com


# Authentication Tokens
@token_donor=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2Q2ZDEzNjQ2ZDM4ODVmYWFiZjhkMSIsInJvbGUiOiJkb25vciIsImlhdCI6MTc0ODk0OTE4MywiZXhwIjoxNzQ5MDM1NTgzfQ.IlT7MN5SXqmtprAUyhtA9N9IDYgUN-sCmCfDcvWdfSM
@token_recipient=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2Q3MDMyNjQ2ZDM4ODVmYWFiZjhkYiIsInJvbGUiOiJyZWNpcGllbnQiLCJpYXQiOjE3NDg5NDkwMzMsImV4cCI6MTc0OTAzNTQzM30.E9F0z-VMVC0OyC54VoasLKNhHSqAb7fTJ3lH-Ed1f1s

# Donation ID and Help Request ID
@donation_id=683ed8dd21167e4388f02034
@help_request_id=683ed8dd21167e4388f02034

### Create Donation
POST {{baseUrl}}/donations
Content-Type: application/json
Authorization: Bearer {{token_donor}}

{
  "title": "Winter Jacket",
  "message": "Hope this helps someone stay warm this winter!",
  "category": "clothing",
  "helpRequest": "{{help_request_id}}"
}

####

### Get All Donations
GET {{baseUrl}}/donations

####

### Get Donation by ID
GET {{baseUrl}}/donations/{{donation_id}}

####

### Update Donation
PUT {{baseUrl}}/donations/{{donation_id}}
Content-Type: application/json
Authorization: Bearer {{token_donor}}

{
  "title": "Winter Jacket (Updated)",
  "message": "Still gently used, added hood"
}

####

### Delete Donation
DELETE {{baseUrl}}/donations/{{donation_id}}
Authorization: Bearer {{token_donor}}

###


### Get donations overview
GET {{baseUrl}}/donations/analytics/overview

### Get Authenticated User's Donations
GET {{baseUrl}}/donations/my
Authorization: Bearer {{token_donor}}
