# Replace the following variables with your actual values
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzcxODBlOWJkNjU5NTgwNTYwMzY1OSIsInJvbGUiOiJkb25vciIsImlhdCI6MTc0ODc3NDA1MCwiZXhwIjoxNzQ4ODYwNDUwfQ.lZIsTqvzQKcQsUrXs_t6SrdIzaLFb_MtlDUJEwzC9ow
@donation_id=683c2b448f52954932b44bda

@help_request_id=68383d01c8bdd3ae36b8a354

### Create Donation
POST http://localhost:3000/donations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Winter Jacket",
  "message": "Hope this helps someone stay warm this winter!",
  "category": "clothing",
  "helpRequest": "{{help_request_id}}"
}

###

### Get All Donations
GET http://localhost:3000/donations
Authorization: Bearer {{token}}

###

### Get Donation by ID
GET http://localhost:3000/donations/{{donation_id}}
Authorization: Bearer {{token}}

###

### Update Donation
PUT http://localhost:3000/donations/{{donation_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Winter Jacket (Updated)",
  "description": "Still gently used, added hood",
  "category": "clothing"
}
###

### Delete Donation
DELETE http://localhost:3000/donations/{{donation_id}}
Authorization: Bearer {{token}}

###


### Get donations overview
GET http://localhost:3000/donations/analytics/overview

### Get Authenticated User's Donations
GET http://localhost:3000/donations/my
Authorization: Bearer {{token}}
