### Base URL
@baseUrl=https://not-an-api.com


### Recipient Token
@token_recipient=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2Q3MDMyNjQ2ZDM4ODVmYWFiZjhkYiIsInJvbGUiOiJyZWNpcGllbnQiLCJpYXQiOjE3NDg5NDgxNTgsImV4cCI6MTc0OTAzNDU1OH0.5hUjo4zkKfPy4Lo8Ikl6N2CgeLwU243RcIRiuN1PmmI

### Donor Token
@token_donor=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2Q2ZDEzNjQ2ZDM4ODVmYWFiZjhkMSIsInJvbGUiOiJkb25vciIsImlhdCI6MTc0ODk0ODM3MiwiZXhwIjoxNzQ5MDM0NzcyfQ.RKJLV6XTVRw3EnMYtNba2EJo7a2lbsZoZU4lGsAEuRs

### Help Request ID
@help_request_id=683ed4cb21167e4388f0200a

### Create Help Request
POST {{baseUrl}}/help-requests
Content-Type: application/json
Authorization: Bearer {{token_recipient}}

{
  "title": "Need clothes for winter",
  "description": "I am looking for warm clothes for my kids.",
  "category": "clothing"
}

### Get All Help Requests
GET {{baseUrl}}/help-requests

### Get Help Request by ID
GET {{baseUrl}}/help-requests/{{help_request_id}}

### Update Help Request
PUT {{baseUrl}}/help-requests/{{help_request_id}}
Content-Type: application/json
Authorization: Bearer {{token_donor}}

{
  "title": "Need warmer winter jackets",
  "description": "Preferably for ages 0-5."
}

### Delete Help Request
DELETE {{baseUrl}}/help-requests/{{help_request_id}}
Authorization: Bearer {{token_recipient}}

### Get Open Help Requests
GET {{baseUrl}}/help-requests/open

### Get logged-in user's Help Requests
GET {{baseUrl}}/help-requests/my
Authorization: Bearer {{token_recipient}}